### ISSUE TITLE
netcdf as a prerequisite

### ISSUE THREAD

**Issue by HWR-llc** [dsi-llc/EFDCPlus_Stable#1]
I'm working on this with Windows using Visual Studio 2022 Community Edition

It compiles successfully with this message:
```
1EFDCPlus_MPI_10.4.0 - 0 error(s), 350 warning(s)
========== Build 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
But I would then get this error message:
![image](https://user-images.githubusercontent.com/10170000/150848774-0d348e53-cbfd-4d9a-88fc-384b1654edf8.png)

I installed [netCDF-C for Windows](https://www.unidata.ucar.edu/software/netcdf/docs/winbin.html) and once it was added to the path, the error message goes away. 

netCDF could be added as one of the prerequisites described in the ReadMe.md.

**Comment by perspicacious-one** [comment]
Yes there needs to be more information for windows setup. It will be added.

**Comment by cocomice** [comment]
@HWR-llc  I also encountered this issue. How did you solve it? adding the netcdf4's `bin` folder to Windows' system path? Which version of netcdf4 did you install?  thanks in advance.

**Comment by HWR-llc** [comment]
Yes I added NETCDF 4.8 and added it to the system path. That did not fix
all the problems. I needed additional files from DSI as well.

Matt
Matt Hodge, PE
[image:  Hodge.WaterResources, LLC] <http://hodgewaterresources.com/>
tel: 803.606.8343 <+18036068343>
9‌5 Arlington St. | Bri‌ghton, MA 021‌35
web: HodgeWaterResources.com <http://hodgewaterresources.com/>

**Comment by perspicacious-one** [comment]
@cocomice,
You can get the required dlls here if needed: https://github.com/dsi-llc/EFDCPlus/releases

**Comment by cocomice** [comment]
@perspicacious-one  ok, thank you very much !
