### ISSUE TITLE
trouble in installing NetCDF

### ISSUE THREAD

**Issue by April312427** [dsi-llc/EFDCPlus_Stable#7]
Hello,

I am having trouble in installing NetCDF.

Here is the error after "Run config.sh"

>  "error: Fortran could not compile .f90 files"

Any clue may be very helpful! And thanks a lot!

**Comment by April312427** [comment]
I found that the problem may be that the “intel.oneapi.mpiifort” is not installed.

So, if anyone has solution or clue, I would be very thankful!!!

**Comment by perspicacious-one** [comment]
Make sure you have installed the Intel Oneapi HPC toolkit and have run the intel script to load the correct environment variables
